# Every time a PR is opened, automatically add a commit which adds the title
# of the PR to the changelog.

name: Update changelog

on:
  pull_request:
    types: [opened]

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      ref: ${{ github.event.pull_request.head.ref }}
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gitchangelog
    - name: Generate updated changelog
      run: |
        gitchangelog > CHANGELOG.rst
    - name: Commit files
      run: |
        git config --local user.email "changelogger@py-libhdate.org"
        git config --local user.name "Py-libhdate Changelogger"
        git commit -am "Updating changelog"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
